CREATE USER test00 IDENTIFIED BY 12345 ACCOUNT UNLOCK;
GRANT RESOURCE, CONNECT TO test00;
ALTER USER test00 DEFAULT TABLESPACE USERS;



CREATE ROLE testrole;
GRANT UNLIMITED TABLESPACE, CREATE SESSION TO testrole;
GRANT testrole TO test00;

CREATE TABLE emptest1
AS 
    SELECT
        *
    FROM
    scott.emp

;

ALTER TABLE emptest1
ADD CONSTRAINT EMP_NO_PK PRIMARY KEY(empno)
;

ALTER TABLE emptest1
MODIFY ename CONSTRAINT EMP_NAME_NN NOT NULL
;

ALTER TABLE EMPTEST1
MODIFY JOB CONSTRAINT EMP_JOB_NN NOT NULL;

ALTER TABLE emptest1
MODIFY hiredate CONSTRAINT EMPTE_MGR_NN NOT NULL;

ALTER TABLE EMPTEST1
drop CONSTRAINT EMPTE_MGR_NN;

